<?php

$labels = array();
$labels['smtp_settings_header'] = 'Configuració SMTP';
$labels['use_default_smtp_server'] = 'Utilitza el servidor SMTP per defecte';
$labels['smtp_host'] = 'IP/Nom + Port Servidor';
$labels['smtp_user'] = 'Nom Usuari';
$labels['smtp_pass'] = 'Contrassenya';
$labels['smtp_pass2'] = 'Repeteix la contrassenya';
$labels['smtp_settings_not_available'] = "Cal emmagatzemar primer, per a poder configurar l'accés SMTP.";
$labels['smtp_passwords_mismatch'] = 'Les contrasenyes no coincideixen';

?>
