<?php

$labels = array();
$labels['smtp_settings_header'] = 'SMTP Einstellungen';
$labels['use_default_smtp_server'] = 'Den voreingestellten SMTP Server verwenden';
$labels['smtp_server'] = 'Server IP/Hostname + Port (Für Verschlüsselung Präfix ssl:// oder tls:// nutzen)';
$labels['smtp_user'] = 'Benutzername';
$labels['smtp_pass'] = 'Passwort';
$labels['smtp_pass2'] = 'Passwort wiederholen';
$labels['smtp_settings_not_available'] = 'Bitte erst speichern, bevor die SMTP Einstellungen vorgenommen werden können.';
$labels['smtp_passwords_mismatch'] = 'Die eingegebenen Passworte stimmen nicht überein.';

?>
