<?php

$labels = array();
$labels['smtp_settings_header'] = 'SMTP Einstellungen';
$labels['use_default_smtp_server'] = 'Den voreingestellten SMTP Server verwenden';
$labels['smtp_server'] = 'SMTP Server IP/Hostname';
$labels['smtp_port'] = 'SMTP Server Port';
$labels['smtp_user'] = 'SMTP Server Benutzername';
$labels['smtp_pass'] = 'SMTP Server Passwort';
$labels['smtp_auth_type'] = 'SMTP Server Auth Type (optional)';
$labels['smtp_helo_host'] = 'SMTP Helo Hostname (optional)';
$labels['smtp_settings_not_available'] = 'Bitte erst Speichern, bevor die SMTP Einstellunge vorgenommen werden können.';

?>
