<?php

$labels = array();
$labels['smtp_settings_header'] = 'SMTP Settings';
$labels['use_default_smtp_server'] = 'Use the default SMTP server';
$labels['smtp_host'] = 'Server IP/Hostname + Port (For encryption use prefix ssl:// or tls://)';
$labels['smtp_user'] = 'Username';
$labels['smtp_pass'] = 'Password';
$labels['smtp_pass2'] = 'Repeat Password';
$labels['smtp_settings_not_available'] = 'Please save first to edit the SMTP settings.';
$labels['smtp_passwords_mismatch'] = 'The passwords do not match.';

?>
