<?php

$labels = array();
$labels['smtp_settings_header'] = 'SMTP Settings';
$labels['use_default_smtp_server'] = 'Use the default SMTP server';
$labels['smtp_server'] = 'SMTP Server IP/Hostname';
$labels['smtp_port'] = 'SMTP Server Port';
$labels['smtp_user'] = 'SMTP Server Username';
$labels['smtp_pass'] = 'SMTP Server Password';
$labels['smtp_auth_type'] = 'SMTP Server Auth Type';
$labels['smtp_helo_host'] = 'SMTP Helo Hostname';
$labels['smtp_settings_not_available'] = 'Please save first to edit the SMTP settings.';

?>
