<?php

$labels = array();
$labels['smtp_settings_header'] = 'Configuración SMTP';
$labels['use_default_smtp_server'] = 'Utiliza el servidor SMTP por defecto';
$labels['smtp_server'] = 'IP/Nombre Servidor';
$labels['smtp_port'] = 'Puerto Servidor';
$labels['smtp_user'] = 'Nombre Usuario';
$labels['smtp_pass'] = 'Contraseña';
$labels['smtp_settings_not_available'] = 'Es necesario guardar primero para poder configurar el acceso SMTP.';
$labels['smtp_passwords_mismatch'] = 'Haz introducido dos contraseñas diferentes.';

?>
