<?php

$labels = array();
$labels['smtp_settings_header'] = 'Paramètres SMTP';
$labels['use_default_smtp_server'] = 'Utiliser le serveur SMTP par défaut';
$labels['smtp_server'] = 'IP du serveur / Nom de l\'hôte + Port du serveur';
$labels['smtp_user'] = 'Nom d\'utilisateur';
$labels['smtp_pass'] = 'Mot de passe';
$labels['smtp_pass2'] = 'Répéter le mot de passe';
$labels['smtp_settings_not_available'] = 'Merci d\'enregistrer avant d\'éditer les paramètres SMTP.';
$labels['smtp_passwords_mismatch'] = 'Les mots de passe ne correspondent pas.';

?>
