<?php

$labels = array();
$labels['smtp_settings_header'] = 'SMTP設定';
$labels['use_default_smtp_server'] = '既定のSMTPサーバを使用する';
$labels['smtp_server'] = 'サーバ名';
$labels['smtp_port'] = 'ポート';
$labels['smtp_user'] = 'ユーザ名';
$labels['smtp_pass'] = 'パスワード';
$labels['smtp_pass2'] = 'パスワード再入力';
$labels['smtp_settings_not_available'] = 'SMTP設定を編集するには最初に保存してください。';
$labels['smtp_passwords_mismatch'] = 'パスワードが一致していません';

?>
