<?php

$labels = array();
$labels['smtp_settings_header'] = 'Ustawienia SMTP';
$labels['use_default_smtp_server'] = 'Użyj domyślnego serwera SMTP';
$labels['smtp_server'] = 'IP/Nazwa hosta serwera (aby skorzystać z szyfrowania użyj prefiksu ssl:// lub tls://)';
$labels['smtp_port'] = 'Port serwera';
$labels['smtp_user'] = 'Nazwa użytkownika';
$labels['smtp_pass'] = 'Hasło';
$labels['smtp_pass2'] = 'Powtórz hasło';
$labels['smtp_settings_not_available'] = 'Zapisz tożsamość, aby móc edytować ustawienia SMTP.';
$labels['smtp_passwords_mismatch'] = 'Hasła nie zgadzają się.';

?>
